import { Trip } from '@/types'

export const seedTrip: Trip = {
  id: 'seed-001',
  name: 'Thailand — Bangkok & Koh Samui',
  currency: 'THB',
  estimatedTotal: 42800,
  seasonalNote: 'Songkran Festival (Thai New Year) — Apr 13–15. Expect street water fights, closures near Silom & Khao San. Book transport early.',
  preferences: {
    destinations: ['Bangkok', 'Koh Samui'],
    startDate: '2026-04-05',
    endDate: '2026-04-15',
    days: 10,
    travelStyle: 'Mid-range comfort',
    budget: '฿2,000–5,000/night',
    activities: ['Beach & water', 'Food & street eats', 'Off-beat / local'],
    travellerType: 'Solo',
  },
  days: [
    {
      dayNumber: 1,
      date: '2026-04-05',
      label: 'Bangkok arrival',
      status: 'full',
      city: 'Bangkok',
      stops: [
        {
          id: 'd1-hotel',
          type: 'hotel',
          time: '14:00',
          duration: 60,
          title: 'Check in — Lub d Silom Bangkok',
          subtitle: 'Silom · 4 nights · ฿1,190/night',
          price: 1190,
          currency: 'THB',
          location: 'Silom',
          tags: ['BTS walkable', 'Rooftop', 'Free lockers', 'Solo-friendly'],
          whyChosen: 'Best-rated social hostel in Silom under ฿1,500. 4 min walk to BTS, rooftop bar, free luggage storage. Silom puts you central for Songkran without Khao San tourist traps.',
          source: 'system',
          imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&h=300&fit=crop&q=80',
          alternatives: [
            { id: 'alt-1a', name: 'Samsen Street Hotel', price: 980, reason: 'Quieter, near old town. Less central for transport.', imageUrl: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=300&h=200&fit=crop&q=80' },
            { id: 'alt-1b', name: 'ibis Sukhumvit 4', price: 1450, reason: 'More comfort, nightlife zone. Noisier at night.', imageUrl: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=300&h=200&fit=crop&q=80' },
            { id: 'alt-1c', name: 'The Standard Bangkok', price: 4200, reason: 'Splurge option with rooftop pool. Great views.', imageUrl: 'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=300&h=200&fit=crop&q=80' },
            { id: 'alt-1d', name: 'Hansar Bangkok', price: 3100, reason: 'Boutique feel, all-suite, great breakfast included.', imageUrl: 'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=300&h=200&fit=crop&q=80' },
            { id: 'alt-1e', name: 'Lub d Siam Square', price: 890, reason: 'Same brand, Siam location — closer to shopping & MBK.', imageUrl: 'https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=300&h=200&fit=crop&q=80' },
          ],
        },
        {
          id: 'd1-transit-1',
          type: 'transit',
          time: '16:30',
          duration: 20,
          title: 'BTS Silom → Asok · 15 min · ฿32',
          subtitle: 'Silom line → Sukhumvit line transfer',
          price: 32,
          currency: 'THB',
          location: 'Silom',
          localIntel: 'AIS 30-day unlimited SIM at 7-Eleven near Asok exit 3 = ฿299. Airport counters charge ฿599 for same plan. Takes 3 min.',
          source: 'system',
        },
        {
          id: 'd1-food-1',
          type: 'food',
          time: '18:00',
          duration: 90,
          title: 'Pier 21 food court — Terminal 21 Asok',
          subtitle: '5th floor · ฿80–150/dish · Token system',
          price: 150,
          currency: 'THB',
          location: 'Asok',
          tags: ['Local pricing', 'No markup', 'A/C', '40+ stalls'],
          whyChosen: 'You said food and local eats matter. Pier 21 is where Bangkok office workers eat — local pricing, 40+ stalls. Not a tourist trap despite being in a mall.',
          source: 'system',
          imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&h=300&fit=crop&q=80',
          closingTime: '22:00',
        },
        {
          id: 'd1-activity-1',
          type: 'activity',
          time: '20:00',
          duration: 90,
          title: 'Lumpini Park evening walk + Soi 33',
          subtitle: 'Free · 20 min walk from Asok',
          price: 0,
          currency: 'THB',
          location: 'Lumpini',
          tags: ['Free', 'Low effort', 'Jet lag friendly'],
          localIntel: 'Soi 33 (Sukhumvit) has live jazz bars with locals — Saxophone Pub is a Bangkok institution. Avoid Soi 11 tonight, heavily tourist-priced during Songkran week.',
          source: 'system',
          imageUrl: 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=600&h=300&fit=crop&q=80',
        },
      ],
    },
    {
      dayNumber: 2,
      date: '2026-04-06',
      label: 'Temples + Yaowarat',
      status: 'full',
      city: 'Bangkok',
      stops: [
        {
          id: 'd2-activity-1',
          type: 'activity',
          time: '08:00',
          duration: 120,
          title: 'Wat Pho — Reclining Buddha',
          subtitle: 'Rattanakosin Island · ฿200 entry',
          price: 200,
          currency: 'THB',
          location: 'Rattanakosin',
          tags: ['Cultural', 'UNESCO', 'Morning recommended'],
          whyChosen: 'Arrive before 10am to beat tour groups. The 46m reclining Buddha is genuinely stunning and less crowded than Grand Palace.',
          localIntel: 'Free sarong wrap at entrance — no need to buy. Wear shoes that slip off easily.',
          source: 'system',
          imageUrl: 'https://images.unsplash.com/photo-1563492065-b4b7f9a48a07?w=600&h=300&fit=crop&q=80',
          closingTime: '18:30',
        },
        {
          id: 'd2-transit-1',
          type: 'transit',
          time: '10:00',
          duration: 30,
          title: 'Chao Phraya ferry to Chinatown · ฿15',
          subtitle: 'Orange flag boat · 20 min scenic ride',
          price: 15,
          currency: 'THB',
          location: 'Rattanakosin',
          localIntel: 'Take the orange-flag boat, not the tourist boat (฿50). Same river, same stops, 3x cheaper.',
          source: 'system',
        },
        {
          id: 'd2-food-1',
          type: 'food',
          time: '12:00',
          duration: 90,
          title: 'Yaowarat Road dim sum lunch',
          subtitle: 'Chinatown · ฿150–300/person',
          price: 200,
          currency: 'THB',
          location: 'Chinatown',
          tags: ['Street eats', 'Local', 'Bustling'],
          whyChosen: 'Yaowarat at lunch has proper Bangkok-Chinese food — roast duck, dim sum, fresh seafood. Nothing like the evening tourist version.',
          localIntel: 'T&K Seafood on Yaowarat Rd has the best crab fried rice at ฿180. Queue, but worth it.',
          source: 'system',
          imageUrl: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=600&h=300&fit=crop&q=80',
          closingTime: '22:00',
        },
        {
          id: 'd2-activity-2',
          type: 'activity',
          time: '14:30',
          duration: 150,
          title: 'Wat Arun (Temple of Dawn)',
          subtitle: 'West bank · ฿100 · Cross-river ferry ฿4',
          price: 100,
          currency: 'THB',
          location: 'Thonburi',
          tags: ['Iconic', 'River views', 'Photogenic'],
          localIntel: 'Cross by longtail from Tha Tien pier for ฿4. Stay until close at 17:30 — the temple glows gold at sunset. Best photos from the east bank after crossing back.',
          source: 'system',
          imageUrl: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=600&h=300&fit=crop&q=80',
          closingTime: '17:30',
        },
        {
          id: 'd2-food-2',
          type: 'food',
          time: '19:00',
          duration: 120,
          title: 'Yaowarat Night Market — street seafood',
          subtitle: 'Chinatown · ฿200–500/person',
          price: 350,
          currency: 'THB',
          location: 'Chinatown',
          tags: ['Night market', 'Seafood', 'Iconic'],
          whyChosen: 'Yaowarat at night is one of Bangkok\'s best food experiences. Grilled seafood, fresh noodles, and mango sticky rice at the stalls.',
          source: 'system',
          imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&h=300&fit=crop&q=80',
          closingTime: '23:00',
        },
      ],
    },
    {
      dayNumber: 3,
      date: '2026-04-07',
      label: 'Or Tor Kor + Siam',
      status: 'partial',
      city: 'Bangkok',
      stops: [
        {
          id: 'd3-activity-1',
          type: 'activity',
          time: '09:00',
          duration: 150,
          title: 'Or Tor Kor Market',
          subtitle: 'Mo Chit BTS · Free entry · Premium Thai produce',
          price: 0,
          currency: 'THB',
          location: 'Mo Chit',
          tags: ['Market', 'Open daily', 'Local'],
          whyChosen: 'Or Tor Kor is Bangkok\'s best fresh market — premium Thai produce, incredible ready-to-eat food, and almost zero tourist presence. Right next to Mo Chit BTS.',
          localIntel: 'Bring cash only. The grilled pork skewers and coconut ice cream near the entrance are unmissable. Go early — vendors start selling out by 11am.',
          source: 'system',
          imageUrl: 'https://images.unsplash.com/photo-1526495124232-a04e1849168c?w=600&h=300&fit=crop&q=80',
          closingTime: '18:00',
        },
        {
          id: 'd3-food-1',
          type: 'food',
          time: '13:00',
          duration: 60,
          title: 'Siam Square lunch — Jay Fai area',
          subtitle: 'Siam · ฿200–400',
          price: 300,
          currency: 'THB',
          location: 'Siam',
          tags: ['Michelin', 'Crab omelette', 'Queue expected'],
          localIntel: 'Jay Fai (฿1,000+ per dish, Michelin star) needs booking weeks ahead. Instead try Thip Samai pad thai on Maha Chai Rd — authentic, ฿60.',
          source: 'system',
          imageUrl: 'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=600&h=300&fit=crop&q=80',
          closingTime: '21:00',
        },
        {
          id: 'd3-activity-2',
          type: 'activity',
          time: '15:00',
          duration: 120,
          title: 'Siam Paragon + Aquarium',
          subtitle: 'Siam BTS · A/C escape · Aquarium ฿590',
          price: 590,
          currency: 'THB',
          location: 'Siam',
          tags: ['Indoor', 'A/C', 'Rainy day option'],
          localIntel: 'Siam Paragon basement supermarket has the best ready-to-eat snacks at local prices. Skip the aquarium if budget-watching.',
          source: 'system',
          imageUrl: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=600&h=300&fit=crop&q=80',
          closingTime: '21:00',
        },
      ],
    },
    {
      dayNumber: 4,
      date: '2026-04-08',
      label: 'Songkran at Silom',
      status: 'full',
      city: 'Bangkok',
      stops: [
        {
          id: 'd4-activity-1',
          type: 'activity',
          time: '10:00',
          duration: 240,
          title: 'Songkran Water Festival — Silom Road',
          subtitle: 'Free · BYO water gun · All day event',
          price: 0,
          currency: 'THB',
          location: 'Silom',
          tags: ['Festival', 'Iconic', 'Wet!', 'Cultural'],
          whyChosen: 'April 8 is pre-Songkran — slightly less chaotic than Apr 13 peak but full street parties on Silom already. Your hotel is walking distance.',
          localIntel: 'Waterproof phone case essential (buy at MBK for ฿50). Wear clothes you don\'t mind getting soaked. Leave valuables at hotel.',
          source: 'system',
          imageUrl: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?w=600&h=300&fit=crop&q=80',
          closingTime: '22:00',
        },
        {
          id: 'd4-food-1',
          type: 'food',
          time: '14:00',
          duration: 60,
          title: 'Street food near Silom — recovery lunch',
          subtitle: 'Silom Soi 20 · ฿80–150',
          price: 120,
          currency: 'THB',
          location: 'Silom',
          tags: ['Casual', 'Close to hotel'],
          source: 'system',
          closingTime: '20:00',
        },
        {
          id: 'd4-activity-2',
          type: 'activity',
          time: '17:00',
          duration: 180,
          title: 'Vertigo & Moon Bar — Rooftop',
          subtitle: 'Banyan Tree Hotel · ฿500+ drinks',
          price: 500,
          currency: 'THB',
          location: 'Silom',
          tags: ['Rooftop', 'Views', 'Splurge evening'],
          whyChosen: 'Best rooftop bar in Bangkok with 360° views. Dress code enforced (no shorts). Songkran week atmosphere is electric.',
          localIntel: 'Opens at 17:00 — arrive early for the sunset. Minimum spend ฿500/person. Book ahead, fills up fast during Songkran week.',
          source: 'system',
          imageUrl: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=600&h=300&fit=crop&q=80',
          closingTime: '01:00',
        },
      ],
    },
    {
      dayNumber: 5,
      date: '2026-04-09',
      label: 'Fly to Koh Samui',
      status: 'partial',
      city: 'Bangkok',
      stops: [
        {
          id: 'd5-transit-1',
          type: 'transit',
          time: '07:00',
          duration: 60,
          title: 'BTS to Suvarnabhumi Airport · ฿45',
          subtitle: 'Airport Rail Link from Phaya Thai · 30 min',
          price: 45,
          currency: 'THB',
          location: 'Suvarnabhumi',
          localIntel: 'Phaya Thai station connects directly to Airport Rail Link. Takes 28 min, runs every 15 min. Don\'t take a taxi — traffic is brutal.',
          source: 'system',
        },
        {
          id: 'd5-transit-2',
          type: 'transit',
          time: '09:30',
          duration: 75,
          title: 'Bangkok BKK → Koh Samui USM · Bangkok Airways',
          subtitle: '1h 15min flight · ~฿2,800 one-way',
          price: 2800,
          currency: 'THB',
          location: 'Koh Samui',
          localIntel: 'Bangkok Airways has a monopoly on this route but their airport lounge is free for all passengers — good breakfast spread.',
          source: 'system',
        },
        {
          id: 'd5-hotel',
          type: 'hotel',
          time: '13:00',
          duration: 60,
          title: 'Check in — The Samui Highlands',
          subtitle: 'Chaweng Noi · Private Pool Villa · 3 nights',
          price: 4200,
          currency: 'THB',
          location: 'Chaweng Noi',
          tags: ['Private pool', 'Ocean view', 'Breakfast included'],
          whyChosen: 'You specifically wanted a private pool. April in Koh Samui = dry season peak. This villa has a plunge pool facing the ocean, ranked #2 for value in the ฿3,500–5,000 range.',
          source: 'system',
          imageUrl: 'https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?w=600&h=300&fit=crop&q=80',
          alternatives: [
            { id: 'alt-5a', name: 'Silavadee Pool Spa Resort', price: 5800, reason: 'Larger infinity pool, more spa options. Premium location on hillside.', imageUrl: 'https://images.unsplash.com/photo-1551882547-ff40c599fb43?w=300&h=200&fit=crop&q=80' },
            { id: 'alt-5b', name: 'Baan Chaweng Beach Resort', price: 2800, reason: 'Right on the beach, no private pool. More social atmosphere.', imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=300&h=200&fit=crop&q=80' },
            { id: 'alt-5c', name: 'Four Seasons Koh Samui', price: 12000, reason: 'Ultimate splurge. Private villa with personal butler.', imageUrl: 'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=300&h=200&fit=crop&q=80' },
            { id: 'alt-5d', name: 'Anantara Bophut Resort', price: 6500, reason: 'Boutique resort on quieter north coast. Excellent beach access.', imageUrl: 'https://images.unsplash.com/photo-1540555700478-4be290a2d46e?w=300&h=200&fit=crop&q=80' },
            { id: 'alt-5e', name: 'InterContinental Koh Samui', price: 8200, reason: 'Clifftop location with panoramic Gulf views and infinity pool.', imageUrl: 'https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?w=300&h=200&fit=crop&q=80' },
          ],
        },
        {
          id: 'd5-activity-1',
          type: 'activity',
          time: '16:00',
          duration: 120,
          title: 'Chaweng Beach afternoon',
          subtitle: 'Walk from villa · Free',
          price: 0,
          currency: 'THB',
          location: 'Chaweng',
          tags: ['Beach', 'Relaxed', 'Snorkelling possible'],
          localIntel: 'Rent a motorbike from the villa reception for ฿200/day — best way to explore the island. Avoid the beach vendors offering jet skis near the north end.',
          source: 'system',
          imageUrl: 'https://images.unsplash.com/photo-1544550581-5f7ceaf7f992?w=600&h=300&fit=crop&q=80',
        },
      ],
    },
    {
      dayNumber: 6,
      date: '2026-04-10',
      label: 'Koh Samui — beach day',
      status: 'full',
      city: 'Koh Samui',
      stops: [
        {
          id: 'd6-activity-1',
          type: 'activity',
          time: '08:00',
          duration: 120,
          title: 'Morning motorbike loop — Big Buddha + fishermen',
          subtitle: 'Rent from villa · ฿200 · ~30km loop',
          price: 200,
          currency: 'THB',
          location: 'Koh Samui',
          tags: ['Active', 'Scenic', 'Local'],
          whyChosen: 'Morning is the best time to visit Big Buddha (Wat Phra Yai) — almost no tourists before 9am. The north coast fishermen market is authentic local life.',
          localIntel: 'Wat Phra Yai (Big Buddha) is free. The seafood market just east of it sells fresh prawns by the kilo — locals buy breakfast here.',
          source: 'system',
          imageUrl: 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=600&h=300&fit=crop&q=80',
        },
        {
          id: 'd6-food-1',
          type: 'food',
          time: '12:00',
          duration: 90,
          title: 'Lamai beachside lunch',
          subtitle: 'Lamai Beach · ฿200–400',
          price: 300,
          currency: 'THB',
          location: 'Lamai',
          tags: ['Beachfront', 'Seafood', 'Views'],
          localIntel: 'Hua Thanon village near Lamai has a Muslim-Thai community with the best goat curry in Samui. 5km south of main Lamai beach.',
          source: 'system',
          imageUrl: 'https://images.unsplash.com/photo-1559494007-9f5847c49d94?w=600&h=300&fit=crop&q=80',
          closingTime: '22:00',
        },
        {
          id: 'd6-activity-2',
          type: 'activity',
          time: '15:00',
          duration: 180,
          title: 'Villa private pool afternoon',
          subtitle: 'Your villa · included',
          price: 0,
          currency: 'THB',
          location: 'Chaweng Noi',
          tags: ['Pool', 'Relax', 'Private'],
          localIntel: 'Ask reception to arrange a coconut smoothie delivery to the pool. The villa cook can also do a private BBQ for ฿600/person.',
          source: 'system',
          imageUrl: 'https://images.unsplash.com/photo-1527515545081-5db817172677?w=600&h=300&fit=crop&q=80',
        },
        {
          id: 'd6-food-2',
          type: 'food',
          time: '19:30',
          duration: 120,
          title: 'The Cliff Bar & Grill — sunset dinner',
          subtitle: 'Chaweng · ฿600–1,200/person',
          price: 900,
          currency: 'THB',
          location: 'Chaweng',
          tags: ['Sunset', 'Seafood', 'Views'],
          whyChosen: 'The Cliff has the best sunset views in Chaweng with fresh seafood caught that morning. Book a window table 24h ahead.',
          source: 'system',
          imageUrl: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&h=300&fit=crop&q=80',
          closingTime: '23:00',
        },
      ],
    },
    {
      dayNumber: 7,
      date: '2026-04-11',
      label: 'Ang Thong snorkel trip',
      status: 'full',
      city: 'Koh Samui',
      stops: [
        {
          id: 'd7-transit-1',
          type: 'transit',
          time: '08:00',
          duration: 30,
          title: 'Speedboat to Ang Thong Marine Park',
          subtitle: 'Na Thon pier · Full-day tour · ฿1,500',
          price: 1500,
          currency: 'THB',
          location: 'Na Thon',
          localIntel: 'Book through your villa — they get 10% off Lomprayah tours. The tour includes snorkel gear, lunch, and kayaking.',
          source: 'system',
        },
        {
          id: 'd7-activity-1',
          type: 'activity',
          time: '09:00',
          duration: 360,
          title: 'Ang Thong Marine Park — full day',
          subtitle: '42 islands · Snorkelling, kayak, viewpoint',
          price: 0,
          currency: 'THB',
          location: 'Ang Thong',
          tags: ['Snorkelling', 'Kayaking', 'UNESCO', 'Stunning'],
          whyChosen: 'Ang Thong is one of Thailand\'s most pristine marine parks — 42 islands with emerald lagoons. April is peak dry season, visibility excellent.',
          localIntel: 'Bring your own reef-safe sunscreen (chemical sunscreen banned in the park). The viewpoint hike is 500 steps but worth every one.',
          source: 'system',
          imageUrl: 'https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?w=600&h=300&fit=crop&q=80',
          closingTime: '17:00',
        },
        {
          id: 'd7-food-1',
          type: 'food',
          time: '19:00',
          duration: 90,
          title: 'Chaweng Beach Road night stalls',
          subtitle: 'Walking street · ฿100–200/dish',
          price: 150,
          currency: 'THB',
          location: 'Chaweng',
          tags: ['Night market', 'Casual', 'Street food'],
          localIntel: 'The mango sticky rice vendor near Ark Bar (north Chaweng) is open until midnight. Best in Samui, ฿80.',
          source: 'system',
          closingTime: '01:00',
        },
      ],
    },
    {
      dayNumber: 8,
      date: '2026-04-12',
      label: 'Koh Samui slow day',
      status: 'partial',
      city: 'Koh Samui',
      stops: [
        {
          id: 'd8-activity-1',
          type: 'activity',
          time: '09:00',
          duration: 150,
          title: 'Thai massage — Samui spa morning',
          subtitle: 'In-villa or Chaweng spa · ฿400–800',
          price: 600,
          currency: 'THB',
          location: 'Chaweng',
          tags: ['Wellness', 'Relaxing', 'Recommended'],
          whyChosen: 'After Ang Thong, your body will thank you. In-villa massage is ฿800 for 90 min — request through reception the night before.',
          localIntel: 'Samui Thai Massage on Chaweng main road offers 2-hour Thai oil massage for ฿400 — same quality as resort, quarter of the price.',
          source: 'system',
          imageUrl: 'https://images.unsplash.com/photo-1540555700478-4be290a2d46e?w=600&h=300&fit=crop&q=80',
          closingTime: '20:00',
        },
        {
          id: 'd8-food-1',
          type: 'food',
          time: '13:00',
          duration: 90,
          title: 'Fisherman\'s Village — Bophut',
          subtitle: 'Bophut · ฿100–300',
          price: 200,
          currency: 'THB',
          location: 'Bophut',
          tags: ['Village', 'Local crafts', 'Food'],
          localIntel: 'Bophut\'s Fisherman\'s Village is genuinely lovely any day — colonial shophouses, local boutiques, real Thai food. Much less touristy than Chaweng. Friday nights have a full walking street market if you\'re here on a Friday.',
          source: 'system',
          imageUrl: 'https://images.unsplash.com/photo-1526495124232-a04e1849168c?w=600&h=300&fit=crop&q=80',
          closingTime: '23:00',
        },
      ],
    },
    {
      dayNumber: 9,
      date: '2026-04-13',
      label: 'Songkran — Koh Samui',
      status: 'full',
      city: 'Koh Samui',
      stops: [
        {
          id: 'd9-activity-1',
          type: 'activity',
          time: '10:00',
          duration: 240,
          title: 'Songkran celebrations — Chaweng',
          subtitle: 'Main beach road · Free',
          price: 0,
          currency: 'THB',
          location: 'Chaweng',
          tags: ['Festival', 'Songkran', 'Water fights', 'Cultural'],
          whyChosen: 'Songkran on Koh Samui is more intimate than Bangkok — beach water fights, local temple ceremonies, and way less crowded.',
          localIntel: 'Songkran is April 13 — the actual Thai New Year. Locals pour scented water on elders\' hands for blessings. Join in, don\'t just watch.',
          source: 'system',
          imageUrl: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?w=600&h=300&fit=crop&q=80',
          closingTime: '22:00',
        },
        {
          id: 'd9-food-1',
          type: 'food',
          time: '15:00',
          duration: 90,
          title: 'Late lunch — seafood BBQ on beach',
          subtitle: 'Chaweng north beach stalls · ฿300–500',
          price: 400,
          currency: 'THB',
          location: 'Chaweng',
          tags: ['Seafood', 'BBQ', 'Beachside'],
          localIntel: 'The beach stalls set up BBQ grills by 14:00 on Songkran. Fresh whole fish ฿250–400 depending on size. Grab Chang beer at ฿80.',
          source: 'system',
          closingTime: '22:00',
        },
        {
          id: 'd9-activity-2',
          type: 'activity',
          time: '19:00',
          duration: 180,
          title: 'Songkran night party — Ark Bar Beach',
          subtitle: 'Chaweng · ฿300–500 drinks',
          price: 400,
          currency: 'THB',
          location: 'Chaweng',
          tags: ['Party', 'Beach', 'Songkran night'],
          localIntel: 'Ark Bar is the main party venue on Songkran night. Fire show on the beach, DJ sets, full moon party vibes. All-inclusive drink packages available at ฿800.',
          source: 'system',
          closingTime: '03:00',
        },
      ],
    },
    {
      dayNumber: 10,
      date: '2026-04-14',
      label: 'Departure day',
      status: 'partial',
      city: 'Koh Samui',
      stops: [
        {
          id: 'd10-activity-1',
          type: 'activity',
          time: '08:00',
          duration: 60,
          title: 'Last swim + villa checkout',
          subtitle: 'Check out by 12:00',
          price: 0,
          currency: 'THB',
          location: 'Chaweng Noi',
          tags: ['Relaxed', 'Farewell'],
          localIntel: 'Ask for late checkout (13:00) — usually granted if villa isn\'t full. No charge, just ask reception the night before.',
          source: 'system',
        },
        {
          id: 'd10-transit-1',
          type: 'transit',
          time: '13:30',
          duration: 30,
          title: 'Taxi to Koh Samui Airport',
          subtitle: '20 min · ฿300 fixed rate',
          price: 300,
          currency: 'THB',
          location: 'Koh Samui Airport',
          localIntel: 'Book villa taxi (฿300) rather than street taxi (฿500+). Bangkok Airways airport has a nice lounge even for departing passengers.',
          source: 'system',
        },
        {
          id: 'd10-transit-2',
          type: 'transit',
          time: '16:00',
          duration: 75,
          title: 'Koh Samui USM → Bangkok BKK',
          subtitle: 'Bangkok Airways · 1h 15min',
          price: 2800,
          currency: 'THB',
          location: 'Bangkok',
          source: 'system',
        },
      ],
    },
  ],
}
